# Build settings
baseurl: 
markdown: kramdown
permalink: pretty
keywords: tripme, tripme lviv, tripme apps, tripme app, tripme startup

port: 3333

exclude: ['README.md']

sass:
  sass_dir: assets/css
  style: :expanded

# for og
# basedomain: http://tripme.github.io
