defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: default
      lang: en
  -
    scope:
      path: _posts/ua
    values:
      layout: default
      lang: ua
  -
    scope:
      path: _posts/ru
    values:
      layout: default
      lang: ru

# Build settings
baseurl: ''
markdown: kramdown
permalink: pretty
keywords: 'tripme, tripme lviv, tripme apps, tripme app, tripme startup'

port: 3333

#languages: ['en', 'ua', 'ru']

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
#exclude_from_localizations: ['assets', 'Gemfile', 'Gemfile.lock']

sass:
  sass_dir: assets/css
  style: :expanded

# for og
# basedomain: http://tripme.github.io




