# Build settings
baseurl: ''
markdown: kramdown
permalink: pretty
keywords: 'tripme, tripme lviv, tripme apps, tripme app, tripme startup'

port: 3333

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
exclude_from_localizations: ['assets', 'Gemfile', 'Gemfile.lock']

sass:
  sass_dir: assets/css
  style: :expanded

languages: ['en', 'ua', 'ru']

# for og
# basedomain: http://tripme.github.io
