# Build settings
baseurl: 
markdown: kramdown
permalink: pretty
keywords: tripme, tripme app, tripme lviv, tripme startup

port: 2525

exclude: ['README.md']

sass:
  sass_dir: assets/css
  style: :expanded

# for og
# basedomain: http://irukanji-music.github.io
