baseurl: ''
exclude: ['README.md', 'CNAME']

sass:
  sass_dir: assets/css
  style: :expanded

# seo
# basedomain: http://tripme.github.io
keywords: 'tripme, tripme lviv, tripme apps, tripme app, tripme startup'

defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: default
      lang: en
  -
    scope:
      path: _posts/ua
    values:
      layout: default
      lang: ua
  -
    scope:
      path: _posts/ru
    values:
      layout: default
      lang: ru





