t:
  en:
    global:
      appstore: '<span>Download on</span><br>AppStore'
      googleplay: '<span>Download on</span><br>Google Play'
      freeapp: 'Free App'
      needhelp: 'Need help? Interested in cooperation?<br>Do you want to help us with advise?'
      mailus: 'Feel free to email us at'
      callus: 'or call'
    home:
      wewillshare: '<span>We will share</span><br>unique routes and<br> secret places of Lviv with you'
      adventure: 'Adventure'
      stroll: 'Stroll'
      lviv: 'Lviv'
      strollwithin: 'Stroll within<br><span>hundreds of stories</span>'
      uniqueplaces: 'Unique places'
      themedrestaurants: 'Themed restaurants'
      themedhotels: 'Тhemed hotels'
      historicalsights: 'Historical sights'
      citystories: 'City history and enigmatic stories<br><span>of Lviv</span>'
      story1title: 'Lviv was a part of eight countries'
      story1descr: 'During the time of its formation Lviv was a part of Kingdom of Galicia–Volhynia, Austria-Hungary, Poland, Russia, under the nazi occupation, West Ukrainian People’s Republic,the Soviet Union and independent Ukraine'
      story2title: 'The town was named after the king’s son'
      story2descr: 'The town was established in 1256 by the King Danil of Galicia, who named it after his son Lev'
      story3title: 'Every year more than a hundred of festivals take place in Lviv'
      story3descr: 'There are more than 2500 historical and architectural monuments preserved in the city. Since 1998 Lviv is included into UNESCO world heritage'
      story4title: 'Lviv has the biggest number of monuments'
      story4descr: 'Traditional festivals of Lviv include those of classical music, street theater, coffee, chocolate. Lviv has also been a destination of one of the world greatest jazz festivals for two years.'
      manyother: 'And many other fascinating<br>festivals, stories and adventures'
    about:
      startwithus: 'We fill cities with fascinating stories.<br><span>Start an adventure with us</span>'
      createroutes: 'Create routes with us'
      helpus: 'Help us create routes in your city'
      contactus: 'Contact us'
      meetourteam: 'Meet our team!'
      pivniuk: 'Аnton Pivniuk'
      pivniukposition: 'CEO, UX & Design Maestro'
      domnikov: 'Vitaliy Domnikov'
      domnikovposition: 'CTO'
      makhotina: 'Regina Makhotina'
      makhotinaposition: 'COO, Project Manager'
      overchyk: 'Nikita Overchyk'
      overchykposition: 'CMO'
      orlovskyi: 'Іhor Orlovskyi'
      orlovskyiposition: 'Front-end Developer'
      klapak: 'Olya Klapak'
      klapakposition: 'Muse'
      contact: 'Contact'
      address: 'Eurasia Business Centre,<br>75, Zhulyanska str., Kyiv, Ukraine'
      help: 'Help'
    press:
      pressmedia: 'Press & media'
      downloadpresskit: 'Download PressKit'
      aboutus: 'Press About Us'
      ourvideo: 'Our Video'
      pressreleases: 'Press Releases'
      branding: 'Branding'
  ua:
    global:
      appstore: '<span>Завантажити з</span><br>Appstore'
      googleplay: '<span>Завантажити з</span><br>Google Play'
      freeapp: 'Додаток безкоштовний'
      needhelp: 'Потрібна допомога? Хочете співпрацювати?<br>Бажаєте допомогти нам порадою?'
      mailus: 'Не соромтесь, пишіть нам на'
      callus: 'або телефонуйте'
    home:
      wewillshare: '<span>Ми покажемо</span><br>Унікальні маршрути та<br>таємні місця Львова'
      adventure: 'Пригоди'
      stroll: 'Прогулянка'
      lviv: 'Львів'
      strollwithin: 'Прогуляйтесь містом<br><span>серед сотен історій</span>'
      uniqueplaces: 'Унікальні місця'
      themedrestaurants: 'Тематичні ресторани'
      themedhotels: 'Тематичні готелі'
      historicalsights: 'Історичні пам’ятки'
      citystories: 'Цікаві історії та таємні розповіді<br><span>міста лева</span>'
      story1title: 'Львів перебував у складі восьми держав'
      story1descr: 'Протягом свого становлення місто перебувало у складі Галицько-Волинського князівства, Австро-Угорської імперії, Польщі, Росії, під нацистською окупацією, Західноукраїнської Народної Республіки, Радянського Союзу та Незалежної України'
      story2title: 'Місто названо ім’ям сина короля'
      story2descr: 'Місто було засновано у 1256 році королем Данилом Галицьким, який назвав його в честь свого сина - Лева'
      story3title: 'Щороку у місті відбувається понад 100 фестивалів'
      story3descr: 'Зокрема,у місті збережено 2500 пам’яток історії та архітектури. Окрім того, з 1998 року Львів внесено у світову спадщину ЮНЕСКО'
      story4title: 'У Львові — найбільша кількість пам’яток'
      story4descr: 'Традиційними для Львова є фестивалі класичної музики, вуличного театру, свята кави, шоколаду, пампуха. Також протягом двох років саме у Львові відбувається один з найбільших у світі джазових фестивалів'
      manyother: 'Та ще багато цікавих<br>фестивалів, історій та пригод'
    about:
      startwithus: 'Ми наповнюємо міста цікавими історіями,<br><span>Побувайте в пригодах разом з нами</span>'
      createroutes: 'Створюйте маршрути разом з нами'
      helpus: 'Допоможіть нам і створіть маршрут в вашому місті.'
      contactus: 'Написати нам'
      meetourteam: 'Познайомся з нашою командою!'
      pivniuk: 'Антон Півнюк'
      pivniukposition: 'CEO, UX & Design Maestro'
      domnikov: 'Віталій Домніков'
      domnikovposition: 'CTO'
      makhotina: 'Регіна Махотіна'
      makhotinaposition: 'COO, Project Manager'
      overchyk: 'Нікіта Оверчік'
      overchykposition: 'CMO'
      orlovskyi: 'Ігор Орловський'
      orlovskyiposition: 'Front-end Developer'
      klapak: 'Оля Клапак'
      klapakposition: 'Muse'
      contact: 'Контакти'
      address: 'Бізнес Центр Євразія,<br>75, вул. Жилянська., Київ, Україна'
      help: 'Допомога'
    press:
      pressmedia: 'Преса та медіа'
      downloadpresskit: 'Завантажити PressKit'
      aboutus: 'Преса про нас'
      ourvideo: 'Наше Відео'
      pressreleases: 'Прес-релізи'
      branding: 'Фірмовий стиль'
  ru:
    global:
      appstore: '<span>Скачать с</span><br>Appstore'
      googleplay: '<span>Скачать с<br>Google Play'
      freeapp: 'Бесплатное приложение'
      needhelp: 'Нужна помощь? Хотите сотрудничать?<br>Хотите помочь нам советом?'
      mailus: 'Не стесняйтесь, пишите нам на'
      callus: 'или звоните'
    home:
      wewillshare: '<span>Мы покажем</span><br>Уникальные маршруты и<br>таинственные места Львова'
      adventure: 'Приключения'
      stroll: 'Прогулка'
      lviv: 'Львов'
      strollwithin: 'Прогуляйтесь по городу<br><span>среди сотен историй</span>'
      uniqueplaces: 'Уникальные места'
      themedrestaurants: 'Тематические рестораны'
      themedhotels: 'Тематические отели'
      historicalsights: 'Исторические памятки'
      citystories: 'Интересные истории и таинственные рассказы<br><span>Львова</span>'
      story1title: 'Львов находился в составе восьми государств'
      story1descr: 'В период своего становления город находился в составе Галицко-Волынского княжества, Австро-Венгерской империи, Польши, России, под нацистской оккупацией, Западно-Украинской Народной Республики, Советского Союза и независимой Украины'
      story2title: 'Город назван в честь сына короля'
      story2descr: 'Город был основан в 1256 году королем Данилом Галицким, который назвал его в честь своего сына - Льва'
      story3title: 'Каждый год в городе проходит более 100 фестивалей'
      story3descr: 'В городе сохранено 2500 памяток истории и архитектуры. Кроме того, с 1998 года Львов внесен в число мирового наследия ЮНЕСКО'
      story4title: 'Во Львове — самое большое количество памяток'
      story4descr: 'Традиционными для Львова являются фестивали класической музыки, уличного театра, праздника кофе, шоколада, пампушек. Также, в течение двух лет именно во Львове проходит один из самых грандиозных в мире джазовых фестивалей'
      manyother: 'И еще много интересных<br>фестивалей, историй и приключений'
    about:
      startwithus: 'Мы наполняем города интересными историями,<br><span>Окунитесь в приключения вместе с нами</span>'
      createroutes: 'Создавайте маршруты вместе с нами'
      helpus: 'Помогите нам и создайте маршрут в Вашем городе'
      contactus: 'Написать нам'
      meetourteam: 'Познакомьтесь с нашей командой!'
      pivniuk: 'Антон Пивнюк'
      pivniukposition: 'CEO, UX & Design Maestro'
      domnikov: 'Виталий Домников'
      domnikovposition: 'CTO'
      makhotina: 'Регина Махотина'
      makhotinaposition: 'COO, Project Manager'
      overchyk: 'Никита Оверчик'
      overchykposition: 'CMO'
      orlovskyi: 'Игорь Орловський'
      orlovskyiposition: 'Front-end Developer'
      klapak: 'Оля Клапак'
      klapakposition: 'Muse'
      contact: 'Контакты'
      address: 'Бизнес Центр Евразия,<br>75, ул. Жилянськая., Київ, Україна'
      help: 'Помощь'
    press:
      pressmedia: 'Пресса и медиа'
      downloadpresskit: 'Скачать PressKit'
      aboutus: 'Пресса про нас'
      ourvideo: 'Наше видео'
      pressreleases: 'Прес-релізи'
      branding: 'Фирменный стиль'


